# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_corta', models.IntegerField()),
                ('url_larga', models.CharField(max_length=128)),
            ],
        ),
    ]
